document.documentElement.classList.add('motion-enhanced');
const qs=(s,c=document)=>c.querySelector(s),qsa=(s,c=document)=>[...c.querySelectorAll(s)],reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const header=qs('[data-header]');
function toggleMenu(open){const currentMenu=qs('[data-menu]'),currentButton=qs('[data-menu-button]');document.body.classList.toggle('menu-open',open);currentMenu?.classList.toggle('is-open',open);currentButton?.setAttribute('aria-expanded',String(open));currentMenu?.setAttribute('aria-hidden',String(!open))}
addEventListener('scroll',()=>header?.classList.toggle('is-scrolled',scrollY>24),{passive:true});
qsa('[data-year]').forEach(el=>el.textContent=new Date().getFullYear());
let revealObserver=null;
if(!reduced&&'IntersectionObserver'in window)revealObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');revealObserver.unobserve(entry.target)}}),{threshold:.12,rootMargin:'0px 0px -56px'});
function registerReveals(root=document){qsa('[data-reveal]',root).forEach((element,index)=>{if(element.dataset.revealRegistered)return;element.dataset.revealRegistered='true';element.style.setProperty('--reveal-delay',`${Math.min(index%3,2)*95}ms`);if(revealObserver)revealObserver.observe(element);else element.classList.add('is-visible')})}
window.ETC_registerReveals=registerReveals;registerReveals();
if(!reduced){let queued=false;const clamp=(value,min,max)=>Math.max(min,Math.min(max,value));const updateMotion=()=>{const desktop=innerWidth>850;qsa('[data-parallax]').forEach(element=>{const parent=element.parentElement,rect=parent.getBoundingClientRect();if(rect.bottom<=0||rect.top>=innerHeight)return;const progress=(innerHeight/2-(rect.top+rect.height/2))/innerHeight;if(element.classList.contains('home-hero-media')){element.style.setProperty('--hero-drift',`${desktop?clamp(progress*54,-32,32):0}px`);element.style.setProperty('--hero-scale',desktop?String(1.08+Math.abs(progress)*.025):'1.06');qs('.hero-copy',parent)?.style.setProperty('--hero-text-drift',`${desktop?clamp(progress*-34,-24,24):0}px`)}else if(parent.classList.contains('statement-image')){element.style.setProperty('--statement-drift',`${desktop?clamp(progress*72,-42,42):0}px`);element.style.setProperty('--statement-scale',desktop?String(1.1+Math.abs(progress)*.025):'1.07');qs('[data-reveal]',parent)?.style.setProperty('--statement-text-drift',`${desktop?clamp(progress*-48,-30,30):0}px`)}});qsa('[data-parallax-soft]').forEach(element=>{const rect=element.getBoundingClientRect();if(rect.bottom>0&&rect.top<innerHeight)element.style.setProperty('--soft-parallax',`${desktop?clamp((innerHeight/2-(rect.top+rect.height/2))*.055,-18,18):0}px`)});const aboutImage=qs('.about-image img');if(aboutImage){const rect=aboutImage.parentElement.getBoundingClientRect();if(rect.bottom>0&&rect.top<innerHeight)aboutImage.style.setProperty('--about-drift',`${desktop?clamp((innerHeight/2-(rect.top+rect.height/2))*.04,-16,16):0}px`)}queued=false};const queueMotion=()=>{if(!queued){queued=true;requestAnimationFrame(updateMotion)}};addEventListener('scroll',queueMotion,{passive:true});addEventListener('resize',queueMotion,{passive:true});queueMotion()}
function currentNavPage(){if(document.body.dataset.page==='home'&&location.hash==='#services')return'services';if(document.body.dataset.page==='home'&&location.hash==='#about')return'about';return document.body.dataset.page}
function headerMarkup(active=''){return `<div class="site-container site-header__inner"><a class="brand" href="index.html" aria-label="ETC_PHOTOS home">ETC<span>_</span>PHOTOS</a><nav class="site-nav" aria-label="Primary"><a class="site-nav__link ${active==='home'?'is-active':''}" data-nav-page="home" href="index.html">Home</a><a class="site-nav__link ${active==='work'?'is-active':''}" data-nav-page="work" href="portfolio.html">Work</a><a class="site-nav__link ${active==='services'?'is-active':''}" data-nav-page="services" href="index.html#services">Services</a><a class="site-nav__link ${active==='about'?'is-active':''}" data-nav-page="about" href="index.html#about">About</a><a class="site-nav__link ${active==='book'?'is-active':''}" data-nav-page="book" href="booking.html">Book</a><a class="site-nav__link ${active==='links'?'is-active':''}" data-nav-page="links" href="links.html">Links</a></nav><a class="site-header__cta" href="booking.html">Book a shoot <span>↗</span></a><button class="menu-trigger" data-menu-button aria-expanded="false" aria-controls="site-menu"><span>Menu</span><i></i></button></div>`}
function menuMarkup(){return `<nav class="mobile-nav" id="site-menu" data-menu aria-hidden="true"><div class="site-container mobile-nav__inner"><p>Navigation</p><a href="index.html">Home</a><a href="portfolio.html">Work</a><a href="index.html#services">Services</a><a href="index.html#about">About</a><a href="booking.html">Book</a><a href="links.html">Links</a></div></nav>`}
function footerMarkup(){return `<div class="site-container"><section class="footer-cta" data-reveal><p>Have a car in mind?</p><a href="booking.html">Let’s shoot.<span>↗</span></a></section><div class="footer-grid"><a class="brand light" href="index.html">ETC<span>_</span>PHOTOS</a><div><p>Explore</p><a href="portfolio.html">Work</a><a href="booking.html">Book a shoot</a><a href="links.html">Links</a></div><div><p>Follow</p><a href="https://www.instagram.com/etc_photo5/" target="_blank" rel="noopener noreferrer">Instagram</a><a href="https://www.tiktok.com/@etc_photos" target="_blank" rel="noopener noreferrer">TikTok</a><a href="https://www.youtube.com/@ETC_PHOTOS" target="_blank" rel="noopener noreferrer">YouTube</a><a href="https://www.facebook.com/profile.php?id=61593175831125" target="_blank" rel="noopener noreferrer">Facebook</a></div><div><p>Contact</p><a href="mailto:contact@etcphotos.co.uk">contact@etcphotos.co.uk</a><span>Suffolk · United Kingdom</span></div></div><div class="footer-base"><span>© <b data-year></b> ETC_PHOTOS</span><span>Automotive photography</span></div></div>`}
const headerSlot=qs('[data-header]');if(headerSlot)headerSlot.innerHTML=headerMarkup(currentNavPage());const menuSlot=qs('[data-menu-slot]');if(menuSlot)menuSlot.outerHTML=menuMarkup();const footerSlot=qs('[data-footer]');if(footerSlot)footerSlot.innerHTML=footerMarkup();
function syncActiveNav(){const active=currentNavPage();qsa('[data-nav-page]').forEach(link=>link.classList.toggle('is-active',link.dataset.navPage===active))}addEventListener('hashchange',syncActiveNav);
registerReveals();requestAnimationFrame(()=>document.body.classList.add('motion-ready'));
// Rebind after shared markup insertion.
const liveMenu=qs('[data-menu]'),liveButton=qs('[data-menu-button]');liveButton?.addEventListener('click',()=>toggleMenu(!liveMenu.classList.contains('is-open')));qsa('[data-menu] a').forEach(a=>a.addEventListener('click',()=>toggleMenu(false)));qsa('[data-year]').forEach(el=>el.textContent=new Date().getFullYear());
